<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Recam.Detect\Recam.Detect.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.MTP" Version="10.0.1" />
    <PackageReference Include="Testcontainers" Version="4.15.0" />
    <PackageReference Include="xunit.v3" Version="4.0.1" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Fixtures\**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
